FROM ubuntu:22.04

RUN apt-get update -qq && \
    apt-get install -y -qq --no-install-recommends \
        clang lld llvm-dev libssl-dev pkg-config git curl ca-certificates && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

COPY rockit-toolchain/bin/rockit /usr/local/bin/rockit
COPY rockit-toolchain/share/rockit/rockit_runtime.o /usr/local/share/rockit/rockit_runtime.o
COPY rockit-toolchain/share/rockit/stdlib /usr/local/share/rockit/stdlib

ENV ROCKIT=/usr/local/bin/rockit
ENV RUNTIME=/usr/local/share/rockit/rockit_runtime.o
ENV STDLIB=/usr/local/share/rockit/stdlib

RUN chmod +x /usr/local/bin/rockit && rockit version
